name: AppleWalletClone

options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "16.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_LANGUAGE: ru
    ENABLE_BITCODE: NO
    TARGETED_DEVICE_FAMILY: 1

targets:
  AppleWalletClone:
    type: application
    platform: iOS
    sources:
      - Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.walletclone
        MARKETING_VERSION: 1.2.0
        CURRENT_PROJECT_VERSION: 3
        INFOPLIST_FILE: Config/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        TARGETED_DEVICE_FAMILY: 1
        SWIFT_VERSION: "5.0"
        CODE_SIGN_STYLE: Automatic
        ENABLE_BITCODE: NO

  AppleWalletCloneTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - Tests
    dependencies:
      - target: AppleWalletClone
    settings:
      base:
        SWIFT_VERSION: "5.0"
        GENERATE_INFOPLIST_FILE: YES

schemes:
  AppleWalletClone:
    build:
      targets:
        AppleWalletClone: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - AppleWalletCloneTests
    archive:
      config: Release
